# Generated by Django 4.2.13 on 2024-07-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('compte', '0002_rename_user_userex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userex',
            new_name='User',
        ),
    ]
